import "./globals.css";
import Header from "./component/common/Header/page";
import Footer from "./component/common/Footer/page";
import Hamburger from "./component/home-components/Hamburger";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
    <Header/>
    <html
      lang="en">
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
    </>
  );
}
